### ISSUE TITLE
web.xml中怎么没有配置 spring  的  ContextLoaderListener

### ISSUE THREAD

**Issue by ooxiaohan** [wchb2015/seckill#2]
web.xml中怎么没有配置 spring  的  ContextLoaderListener 反而也能顺利启动呢？ 请指点一下~

**Comment by wchb2015** [comment]
我理解就是Spring中有两种上下文环境-"Application Context和Web Application Context",他们分别对应ContextLoaderListener和ServletDispatcher,且都可以用来配置bean的注入,装配,和AOP,所以只要有一个就OK了.

**Comment by wchb2015** [comment]
DispatchServlet和ContextLoaderListener都可以用来加载spring的上下文,可以一起用,也可以只用一个.不过好的做法是DispatchServlet用来加载controller相关的bean,ContextLoaderListener用来加载service,dao相关的bean.具体到两种加载方式的实现看一下ContextLoaderListener,DispatchServlet的源代码比较好.
